### ISSUE TITLE
Node.js + Lamda

### ISSUE THREAD

**Issue by GreyEcologist** [Krever/lambda-titan-dynamodb-seed#1]
Hey thanks for putting this out there, any chance you could elaborate on how to deploy this integration?

Mainly, does this script launches a Gremlin Server instance? Short of familiarizing myself with scala, how would include that into a node.js lambda?

Best.

**Comment by Krever** [comment]
When you deploy java lambda(scala is compiled to same binary form as java) you package all dependencies with it. TitanDB is also written in java and it is a dependency of this project(defined in build.sbt). When lamba is run, titandb starts in embedded mode in the same process as lambda. 

Only way of using it with node.js is to create separate java lambda with TitanDB api exposed as functions. Then you can call one lambda from the other(node.js one).

Please, tell me if everything is clear now.

**Comment by GreyEcologist** [comment]
Hey Krever! Yep, that makes a lot more sense now, I might as well go the EC2 route! Thanks!
